// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package globals

type Globals struct {
	OrganizationID int64 `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *Globals) GetOrganizationID() int64 {
	if o == nil {
		return 0
	}
	return o.OrganizationID
}
